export {EntryView} from './entry'
export {MenuView} from './menu'
export {ScoreInputView} from './score-input'
export {PrevGamesView} from './prev-games'
export {GlobalSettingsView} from './global-settings'
