parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project: ./tsconfig.json

env:
  browser: true
  node: true
  commonjs: true
  es6: true
  jest: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - prettier/@typescript-eslint

rules:
  getter-return: error
  no-await-in-loop: warn
  no-prototype-builtins: error
  no-template-curly-in-string: warn

  array-callback-return: error
  dot-notation: error
  eqeqeq:
    - error
    - smart
  guard-for-in: error
  no-alert: error
  no-else-return: warn
  no-lone-blocks: error
  no-loop-func: error
  prefer-promise-reject-errors: error
  no-return-await: warn
  yoda:
    - error
    - never
    - exceptRange: true

  linebreak-style: error
  prefer-const: error
  capitalized-comments:
    - error
    - always
    - { ignorePattern: webpackChunkName }
  line-comment-position: error
  no-throw-literal: error
  no-return-assign: error
  no-multi-str: error
  multiline-comment-style: error
  spaced-comment: error
  no-floating-decimal: error
  no-console: off
  # Detected in tsc
  no-unused-vars: off
  prefer-object-spread: error

  "@typescript-eslint/await-thenable": error
  "@typescript-eslint/member-naming": error
  "@typescript-eslint/explicit-function-return-type":
    - 1
    - { allowExpressions: true }
  # Turning off require() check because of webpack config
  "@typescript-eslint/no-var-requires": off
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/no-explicit-any": off
  # This is detected in tsc
  # And linter's cannot detect implicit use of React
  "@typescript-eslint/no-unused-vars": off
