---
parserOptions:
  ecmaVersion: 2017
  sourceType: module
  ecmaFeatures:
    experimentalObjectRestSpread: true
env:
  browser: true
  node: true
  commonjs: true
  es6: true
  jest: true

extends:
 - eslint:recommended

rules:
  getter-return: error
  no-await-in-loop: warn
  no-prototype-builtins: error
  no-template-curly-in-string: warn
  valid-jsdoc: error

  array-callback-return: error
  curly: error
  dot-location:
   - warn
   - property
  dot-notation: error
  eqeqeq:
   - error
   - smart
  guard-for-in: error
  no-alert: error
  no-else-return: warn
  no-lone-blocks: error
  no-loop-func: error
  prefer-promise-reject-errors: error
  no-return-await: warn
  yoda:
   - error
   - never
   - exceptRange: true

  array-bracket-spacing: error
  block-spacing: error
  brace-style: error
  comma-dangle: error
  comma-spacing: error
  eol-last: error
  linebreak-style: error
  semi:
   - error
   - never
  indent:
   - error
   - 2
  keyword-spacing: error
  arrow-spacing: error
  quotes:
   - error
   - single
   - allowTemplateLiterals: false
     avoidEscape: true
  prefer-const: error
  capitalized-comments:
   - error
   - always
   - {ignorePattern: webpackChunkName}
  line-comment-position: error
  no-throw-literal: error
  no-return-assign: error
  no-multi-str: error
  no-multi-spaces: error
  no-trailing-spaces: error
  multiline-comment-style: error
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment: error
  no-floating-decimal: error
  object-curly-spacing: error
  no-console: off
