---
parser: babel-eslint
parserOptions:
  ecmaVersion: 2017
  sourceType: module
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
env:
  browser: true
  node: true
  commonjs: true

plugins:
 - react
 - ava

settings:
  react:
    pragma: h

extends:
 - eslint:recommended
 - plugin:react/recommended
 - plugin:ava/recommended

rules:
  no-template-curly-in-string: warn
  array-callback-return: error
  curly: error
  dot-location:
   - warn
   - property
  dot-notation: error
  eqeqeq:
   - error
   - smart
  no-return-await: warn
  yoda:
   - error
   - never
   - exceptRange: true
  semi:
   - error
   - never
  indent:
   - error
   - 2
  keyword-spacing: error
  arrow-spacing: error
  quotes:
   - error
   - single
   - allowTemplateLiterals: false
     avoidEscape: true
  prefer-const: error
  react/prop-types: off
