parserOptions:
  ecmaVersion: 2018
  sourceType: module
env:
  browser: true
  node: true
  commonjs: true
  es6: true
  jest: true

extends:
  - eslint:recommended
  - prettier

rules:
  getter-return: error
  no-await-in-loop: warn
  no-prototype-builtins: error
  no-template-curly-in-string: warn
  valid-jsdoc: error

  array-callback-return: error
  dot-notation: error
  eqeqeq:
    - error
    - smart
  guard-for-in: error
  no-alert: error
  no-else-return: warn
  no-lone-blocks: error
  no-loop-func: error
  prefer-promise-reject-errors: error
  no-return-await: warn
  yoda:
    - error
    - never
    - exceptRange: true

  linebreak-style: error
  prefer-const: error
  capitalized-comments:
    - error
    - always
    - { ignorePattern: webpackChunkName }
  line-comment-position: error
  no-throw-literal: error
  no-return-assign: error
  no-multi-str: error
  multiline-comment-style: error
  spaced-comment: error
  no-floating-decimal: error
  no-console: off
  no-unused-vars:
    - 2
    - { ignoreRestSiblings: true, argsIgnorePattern: "^_" }
  prefer-object-spread: error
