---
parserOptions:
  ecmaVersion: 6
  sourceType: module
env:
  browser: true
  node: true
  commonjs: true

plugins:
 - tape

extends:
 - eslint:recommended
 - plugin:tape/recommended

rules:
  no-template-curly-in-string: warn
  array-callback-return: error
  curly: error
  dot-location:
   - warn
   - property
  dot-notation: error
  eqeqeq:
   - error
   - smart
  no-return-await: warn
  yoda:
   - error
   - never
   - exceptRange: true
  semi:
   - error
   - never
  indent:
   - error
   - 2
  keyword-spacing: error
  arrow-spacing: error
  quotes:
   - error
   - single
   - allowTemplateLiterals: false
     avoidEscape: true
  prefer-const: error
