image: node:latest

cache:
  paths:
    - node_modules

stages:
  - build
  - deploy

lint:
  script:
    - yarn install --pure-lockfile
    - npm run lint
  stage: build

# Unit test
test:
  script:
    - yarn install --pure-lockfile
    - npm test -- --runInBand
  stage: build

# Compile assets
build:
  script:
    - yarn install --pure-lockfile
    - npm run build:prod
  stage: build
  artifacts:
    paths:
      - dist

# Deploy production artifact to Firebase Hosting (Master deployment)
firebase:
  script:
    - npm -g config set user root # Workaround for EACCES issue when run as root
    - npm install -g firebase-tools
    - firebase deploy --token $FIREBASE_TOKEN
  stage: deploy
  cache:
    key: firebase-tools
    paths:
      - /usr/local/lib/node_modules
  environment:
    name: firebase
    url: https://bridge.holi0317.net
  only:
    - master

# Deploy production artifact to GitLab pages (Staging deployment)
pages:
  script: mkdir public && cp -R dist/* public/
  stage: deploy
  artifacts:
    paths:
      - public
  environment:
    name: staging
    url: https://holi0317.gitlab.io/bridge-calc
  only:
   - staging
