extends: stylelint-config-recommended
rules:
  selector-pseudo-class-no-unknown:
    - true
    - {
        ignorePseudoClasses:
          ["export", "import", "global", "local", "external"],
      }

  # Custom rules
  value-no-vendor-prefix: true
  no-descending-specificity: null
