language: node_js
node_js:
 - "stable"

cache:
  yarn: true
  directories:
  - node_modules

before_install:
 - curl -o- -L https://yarnpkg.com/install.sh | bash
 - export PATH=$HOME/.yarn/bin:$PATH

install:
 - yarn

script:
 - npm run lint
 - npm run test
 - npm run build:prod

deploy:
 - provider: firebase
   skip_cleanup: true
   token:
     secure: $FIREBASE_TOKEN
   on:
     branch: master
 - provider: pages
   skip_cleanup: true
   local_dir: dist
   github_token: $GITHUB_TOKEN
   on:
     branch: master
