language: node_js
node_js:
 - "stable"

cache:
  directories:
  - node_modules
  - bower_components

branches:
  only:
  - master

install:
 - npm install polymer-cli firebase-tools bower
 - bower install
 - node_modules/.bin/polymer build --html.collapseWhitespace
 - cp manifest.json build/bundled/
 - cp manifest.json build/unbundled/

script:
 - node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
