sudo: required

language: node_js
node_js:
 - "stable"

cache:
  directories:
  - node_modules

before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y chromium-browser
 - curl -o- -L https://yarnpkg.com/install.sh | bash
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start

install:
 - yarn

script:
 - npm run lint
 - npm run test
 - npm run build:prod

after_success:
 - cp dist/index.html dist/404.html  # For Firebase. All 404 should serve the index page.

deploy:
 - provider: firebase
   skip_cleanup: true
   token:
     secure: $FIREBASE_TOKEN
   on:
     branch: master
 - provider: pages
   skip_cleanup: true
   local_dir: dist
   github_token: $GITHUB_TOKEN
   on:
     branch: master
