language: node_js
node_js:
 - "stable"

cache:
  directories:
  - node_modules

branches:
  only:
  - master

install:
 - npm install polymer-cli firebase-tools
 - node_modules/.bin/polymer build --html.collapseWhitespace

script:
 - node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"